### ISSUE TITLE
Nested IF statements don't work

### ISSUE THREAD

**Issue by HanryuDR** [joemcbride/outlander-osx#101]
```
if contains("%0", "nocam") then
 {
 var afterprep harness
 var afterharness repeatharness
 var c 3
 if contains("%1", "nocam") then shift
 }
else
 {
 var afterprep charcam
 var afterharness prepwait
 var c 2
 }
```

That script did not work until I removed the IF that's in the {}

**Comment by joemcbride** [comment]
Unfortunately this is a known issue and part of why I want to re-write the script engine.  You can _sometimes_ get them to work when adding additional newlines.  There is also a known issue with the last command within an `if` block - doesn't matter what it is, sometimes doesn't properly work depending on the nesting.

You can also try both the newlines and adding `{}` to the if instead of on a single line.

```
if contains("%0", "nocam") then
 {
   var afterprep harness
   var afterharness repeatharness
   var c 3

   if contains("%1", "nocam") then
   {
      shift
   }

 }
else
 {
    var afterprep charcam
    var afterharness prepwait
    var c 2
 }
```

Possibly related to #66

**Comment by joemcbride** [comment]
For instance, in this [smelt](https://github.com/joemcbride/outlander-osx-scripts/blob/master/smelt.cmd#L70) script, it has a nested if and it works fine.  Just some bugs in how the `if` blocks are parsed and executed.  =/

**Comment by joemcbride** [comment]
Declaring victory on this one.
