### ISSUE TITLE
Add a way to change font

### ISSUE THREAD

**Issue by jmoya-msights** [joemcbride/outlander-osx#72]
Hey. Love the client but would like to change font and size. I couldn't find an option to do so, sorry if it is already available. I can open menu to look at system fonts but can't change.

**Comment by joemcbride** [comment]
You can do it though it is not very straight forward.  You unfortunately cannot do it through the UI yet.  You can change font and size in your `layout.cfg` file.  This file has several entries for each of your defined windows.

Each window has a `fontName`, `fontSize`, `monoFontName` and `monoFontSize`.  You can change those to the font/size that you like.

**Note**:  You will need to edit this file while Outlander is not running, otherwise your changes may get overridden when Outlander closes.

Here is an example of what one of the window settings may look like:
```
{"name":"main","x":0,"timestamp":0,"monoFontName":"Menlo","y":258,"width":1021,"monoFontSize":13,"closedTarget":null,"title":"Story","showBorder":1,"visible":1,"height":432,"fontSize":14,"fontName":"Helvetica"}
```

**Comment by joemcbride** [comment]
Going to close this, let me know if you have any other questions/issues!
