### ISSUE TITLE
Regex misbehaving

### ISSUE THREAD

**Issue by Antendren** [joemcbride/outlander-osx#93]
In regex, the pipe literal `\|` isn't behaving properly.  Consider the following code:
```
var manipulable badger|frog
var temp badger|badger|frog|skeleton|zombie|badger|badger|golem

eval temp replacere("%temp","\|(?!%manipulable)\w*\|","")
echo T:%temp
```
This produces the output `T:badger|badger|frog|skeleton|zombie|badger|badger|golem`
It should match on `|skeleton|` or `|zombie|` (or possibly both), but instead %temp is unchanged.

Also, if I put the literal into a group, I'm pretty sure it's being treated like a disjunction of expressions.  For example:
```
eval temp replacere("abc","b(w|\|)","X")
echo T:%temp
```
This should not match, but it produces the output `T:aXc`.

**Comment by joemcbride** [comment]
So I believe this is also fixed in the new script engine.

The result of the first one shows as : `T:badger|badger|frogzombie|badger|badger|golem`.  I'm not sure that's exactly what you want, but I'm pretty sure that's working correctly with the given input.

Rubular for reference:  http://rubular.com/r/ilKQHm8WLE

The second one correctly does not match.
